#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=24:00:00
#SBATCH --job-name=llama8b_instruct_one_layer_baseline
#SBATCH --output=job_logs/frozen/llama8b_instruct_one_layer_baseline-%A.out

cd $HOME/GateSkip

. jobs/environment.sh

srun python -m experiment \
  --model-name "meta-llama/Llama-3.1-8B-Instruct" \
  --pretrained \
  --eval-batch-size 4 \
  --seq-length 2048 \
  --finetune-mode frozen \
  --trainable-layers -1 \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama8b_instruct_one_layer_baseline \
  --load-from-checkpoint llama8b_instruct_one_layer_baseline \
  --max-hours 16 \
  --project-name gateskip
