#!/bin/bash -l

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --job-name=llama3b_one_layer_baseline
#SBATCH --output=job_logs/frozen/loglikelihood/llama3b_one_layer_baseline-%A.out

cd "$HOME/GateSkip"

. jobs/environment.sh

# srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
#   --model-name "meta-llama/Llama-3.2-3B" \
#   --dataset fineweb \
#   --pretrained \
#   --batch-size 1 \
#   --eval-batch-size 4 \
#   --seq-length 128 \
#   --learning-rate 3e-6 \
#   --warmup-steps 1000 \
#   --lr-decay-steps 6800 \
#   --max-epochs 1 \
#   --finetune-mode frozen \
#   --trainable-layers -1 \
#   --experiment-name llama3b_one_layer_baseline \
#   --save-to-checkpoint llama3b_one_layer_baseline \
#   --max-hours 9 \
#   --project-name gateskip \
#   --enable-logging

srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
  --model-name "meta-llama/Llama-3.2-3B" \
  --pretrained \
  --eval-batch-size 4 \
  --seq-length 2048 \
  --finetune-mode frozen \
  --randomly-skip \
  --trainable-layers -1 \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama3b_one_layer_baseline \
  --load-from-checkpoint llama3b_one_layer_baseline \
  --max-hours 3 \
  --project-name gateskip
