#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --job-name=llama1b_gateskip_frozen
#SBATCH --output=job_logs/frozen/loglikelihood/llama1b_gateskip_frozen-%A.out

cd $HOME/GateSkip

. jobs/environment.sh

# srun python -m experiment \
#   --model-name "meta-llama/Llama-3.2-1B" \
#   --dataset fineweb \
#   --pretrained \
#   --use-gating \
#   --entropy-loss-weight 0.0 \
#   --sparsity-loss-weight 1.0 \
#   --skip-modules \
#   --increasing-threshold \
#   --start-thr-percentile 0.0 \
#   --end-thr-percentile 0.2 \
#   --num-increasing-steps 6800 \
#   --batch-size 1 \
#   --eval-batch-size 8 \
#   --seq-length 128 \
#   --learning-rate 3e-6 \
#   --warmup-steps 1000 \
#   --lr-decay-steps 6800 \
#   --max-epochs 1 \
#   --finetune-mode frozen \
#   --experiment-name llama1b_gateskip_frozen \
#   --save-to-checkpoint llama1b_gateskip_frozen \
#   --max-hours 9 \
#   --project-name gateskip \
#   --enable-logging

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-gating \
  --skip-modules \
  --eval-batch-size 8 \
  --seq-length 2048 \
  --finetune-mode frozen \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama1b_gateskip_frozen \
  --load-from-checkpoint llama1b_gateskip_frozen \
  --max-hours 3 \
  --project-name gateskip
