#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=02:30:00
#SBATCH --job-name=llama1b_pabee
#SBATCH --output=job_logs/loglikelihood/llama1b_pabee-%A.out

cd $HOME/Gating

. jobs/environment.sh

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-early-exit \
  --use-patience-exit \
  --patience 3 \
  --confidence-measure hidden_state \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama1b_pabee \
  --project-name gateskip

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-early-exit \
  --use-patience-exit \
  --patience 3 \
  --confidence-measure softmax \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama1b_pabee \
  --project-name gateskip
