#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=02:30:00
#SBATCH --job-name=llama1b_free
#SBATCH --output=job_logs/loglikelihood/llama1b_free-%A.out

cd $HOME/Gating

. jobs/environment.sh

#srun python -m experiment \
#  --model-name "meta-llama/Llama-3.2-1B" \
#  --dataset csqa_gsm8k_gen \
#  --pretrained \
#  --use-early-exit \
#  --batch-size 1 \
#  --eval-batch-size 16 \
#  --seq-length 4096 \
#  --learning-rate 3e-6 \
#  --warmup-steps 1000 \
#  --lr-decay-steps 6800 \
#  --max-epochs 1 \
#  --finetune-mode full \
#  --experiment-name llama1b_free \
#  --save-to-checkpoint llama1b_free \
#  --project-name gateskip \
#  --enable-logging
 
srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-early-exit \
  --early-exit-method free \
  --use-free-distillation \
  --use-free-speculative-decoding \
  --free-shallow-layers 0 6 \
  --confidence-measure hidden_state \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama1b_free \
  --load-from-checkpoint llama1b-csqa-gsm8k-early-exit \
  --project-name gateskip

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-early-exit \
  --early-exit-method free \
  --use-free-distillation \
  --use-free-speculative-decoding \
  --free-shallow-layers 0 6 \
  --confidence-measure softmax \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama1b_free \
  --load-from-checkpoint llama1b-csqa-gsm8k-early-exit \
  --project-name gateskip

