#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=05:30:00
#SBATCH --job-name=llama1b_skip_layer
#SBATCH --output=job_logs/loglikelihood/llama1b_skip_layer-%A.out

cd $HOME/GateSkip

. jobs/environment.sh

 srun python -m experiment \
   --model-name "meta-llama/Llama-3.2-1B" \
   --dataset csqa_gsm8k_gen \
   --pretrained \
   --use-skip-layer \
   --skip-threshold 0.0 \
   --batch-size 1 \
   --eval-batch-size 16 \
   --seq-length 4096 \
   --learning-rate 3e-6 \
   --warmup-steps 1000 \
   --lr-decay-steps 6800 \
   --max-epochs 1 \
   --finetune-mode full \
   --experiment-name llama1b_skip_layer_loglikelihood \
   --save-to-checkpoint llama1b_skip_layer_loglikelihood \
   --project-name gateskip \
   --enable-logging
 
srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-skip-layer \
  --skip-threshold 0.0 \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama1b_skip_layer_loglikelihood \
  --load-from-checkpoint llama1b_skip_layer_loglikelihood \
  --project-name gateskip

