#!/bin/bash -l

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=06:30:00
#SBATCH --job-name=llama3b_instruct_vector_individual_gate_loglikelihood
#SBATCH --output=job_logs/loglikelihood/llama3b_instruct_vector_individual_gate_loglikelihood-%A.out

cd "$HOME/GateSkip"

. jobs/environment.sh

# srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
#  --model-name "meta-llama/Llama-3.2-3B-Instruct" \
#  --dataset fineweb \
#  --pretrained \
#  --use-gating \
#  --entropy-loss-weight 0.0 \
#  --sparsity-loss-weight 1.0 \
#  --skip-modules \
#  --increasing-threshold \
#  --start-thr-percentile 0.0 \
#  --end-thr-percentile 0.2 \
#  --num-increasing-steps 6800 \
#  --batch-size 1 \
#  --eval-batch-size 16 \
#  --seq-length 512 \
#  --learning-rate 3e-6 \
#  --warmup-steps 1000 \
#  --lr-decay-steps 6800 \
#  --max-epochs 1 \
#  --max-hours 1 \
#  --finetune-mode full \
#  --experiment-name llama3b_instruct_vector_individual_gate_loglikelihood \
#  --save-to-checkpoint llama3b_instruct_vector_individual_gate_loglikelihood \
#  --project-name gateskip \
#  --enable-logging

srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
  --model-name "meta-llama/Llama-3.2-3B-Instruct" \
  --pretrained \
  --use-gating \
  --skip-modules \
  --eval-batch-size 32 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama3b_instruct_vector_individual_gate_loglikelihood \
  --load-from-checkpoint llama3b_instruct_vector_individual_gate_loglikelihood \
  --project-name gateskip
