#!/bin/bash -l

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=04:30:00
#SBATCH --job-name=llama1b_pabee
#SBATCH --output=job_logs/loglikelihood/llama1b_pabee-%A.out

cd "$HOME/GateSkip"

. jobs/environment.sh

srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-early-exit \
  --confidence-measure patience \
  --patience 3 \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama1b_pabee_loglikelihood \
  --project-name gateskip

