#!/bin/bash -l

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --job-name=llama8b_baseline
#SBATCH --output=job_logs/loglikelihood/llama8b_baseline-%A.out

cd "$HOME/GateSkip"

. jobs/environment.sh

srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
  --model-name "meta-llama/Llama-3.1-8B" \
  --dataset fineweb \
  --pretrained \
  --batch-size 1 \
  --eval-batch-size 16 \
  --seq-length 512 \
  --learning-rate 3e-6 \
  --warmup-steps 1000 \
  --lr-decay-steps 6800 \
  --max-epochs 1 \
  --finetune-mode full \
  --max-hours 4 \
  --experiment-name llama8b_baseline \
  --save-to-checkpoint llama8b_baseline \
  --project-name gateskip \
  --use-deepspeed \
  --enable-logging
 
srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
  --model-name "meta-llama/Llama-3.1-8B" \
  --pretrained \
  --eval-batch-size 32 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics commonsense_qa,piqa,mmlu_stem,hellaswag,winogrande,openbookqa,squadv2 \
  --num-fewshot 0 \
  --experiment-name llama8b_baseline_loglik \
  --load-from-checkpoint llama8b_baseline \
  --project-name gateskip
