#!/bin/bash -l

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=02:30:00
#SBATCH --job-name=llama1b_vector_individual_gate_lambada
#SBATCH --output=job_logs/loglikelihood/llama1b_vector_individual_gate_lambada-%A.out

cd "$HOME/GateSkip"

. jobs/environment.sh

srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-gating \
  --skip-modules \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics lambada \
  --num-fewshot 0 \
  --experiment-name llama1b_vector_individual_gate_lambada \
  --load-from-checkpoint llama1b_vector_individual_gate \
  --project-name gateskip

