#!/bin/bash -l

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --job-name=llama8b_instruct_gateskip_frozen
#SBATCH --output=job_logs/frozen/cot/llama8b_instruct_gateskip_frozen-%A.out

cd "$HOME/GateSkip"

. jobs/environment.sh

# srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
#   --model-name "meta-llama/Llama-3.1-8B-Instruct" \
#   --dataset csqa_gsm8k_gen \
#   --pretrained \
#   --use-gating \
#   --entropy-loss-weight 0.0 \
#   --sparsity-loss-weight 1.0 \
#   --skip-modules \
#   --increasing-threshold \
#   --start-thr-percentile 0.0 \
#   --end-thr-percentile 0.2 \
#   --num-increasing-steps 6800 \
#   --batch-size 2 \
#   --eval-batch-size 4 \
#   --seq-length 2048 \
#   --learning-rate 1e-4 \
#   --warmup-steps 1000 \
#   --lr-decay-steps 6800 \
#   --max-epochs 5 \
#   --finetune-mode frozen \
#   --experiment-name llama8b_instruct_gateskip_frozen \
#   --save-to-checkpoint llama8b_instruct_gateskip_frozen \
#   --max-hours 9 \
#   --project-name gateskip \
#   --enable-logging

srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
  --model-name "meta-llama/Llama-3.1-8B-Instruct" \
  --pretrained \
  --use-gating \
  --skip-modules \
  --eval-batch-size 4 \
  --seq-length 2048 \
  --finetune-mode frozen \
  --mode evaluate \
  --evaluation-metrics csqa_gen,gsm8k \
  --num-fewshot 0 \
  --experiment-name llama8b_instruct_gateskip_frozen \
  --load-from-checkpoint llama8b_instruct_gateskip_frozen \
  --max-hours 3 \
  --project-name gateskip

