#!/bin/bash -l

#SBATCH --job-name=GateSkip-frozen-backbone-MLP-shared
#SBATCH --output=job_logs/GateSkip-frozen-backbone-MLP-shared/cot_%j.txt
#SBATCH --partition=a100
#SBATCH --gres=gpu:a100:1 -C a100_80
#SBATCH --time=23:00:00
#SBATCH --nodes=1

cd "$HOME/GateSkip"

. jobs/environment.sh
. jobs/job_common.sh

run_job "GateSkip-frozen-backbone-MLP-shared" "cot" "GateSkip-frozen-backbone-MLP-shared" true
