#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=8:00:00
#SBATCH --job-name=llama1b_gateskip_l1_sw100
#SBATCH --output=job_logs/l1-loss/llama1b_gateskip_l1_sw100-%A.out

cd $HOME/GateSkip

. jobs/environment.sh

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --dataset csqa_gsm8k_gen \
  --pretrained \
  --use-gating \
  --entropy-loss-weight 0.0 \
  --sparsity-loss-weight 100.0 \
  --sparsity-loss-type l1 \
  --skip-modules \
  --increasing-threshold \
  --start-thr-percentile 0.0 \
  --end-thr-percentile 0.2 \
  --num-increasing-steps 6800 \
  --batch-size 1 \
  --eval-batch-size 16 \
  --seq-length 4096 \
  --learning-rate 3e-6 \
  --warmup-steps 1000 \
  --lr-decay-steps 6800 \
  --max-epochs 1 \
  --max-hours 8 \
  --finetune-mode full \
  --experiment-name llama1b_gateskip_l1_sw100 \
  --save-to-checkpoint llama1b_gateskip_l1_sw100 \
  --project-name gateskip \
  --enable-logging

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-gating \
  --sparsity-loss-type l1 \
  --skip-modules \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics csqa_gen,gsm8k,piqa_gen \
  --num-fewshot 0 \
  --experiment-name llama1b_gateskip_l1_sw100 \
  --load-from-checkpoint llama1b_gateskip_l1_sw100 \
  --project-name gateskip
