#!/bin/bash -l

#SBATCH --job-name=random-skipping-baseline-Llama-3b-Instruct
#SBATCH --output=job_logs/random-skipping-baseline-Llama-3b-Instruct/cot_%j.txt
#SBATCH --partition=a100
#SBATCH --gres=gpu:a100:1 -C a100_80
#SBATCH --time=23:00:00
#SBATCH --nodes=1

cd "$HOME/GateSkip"

. jobs/environment.sh
. jobs/job_common.sh

run_job "random-skipping-baseline-Llama-3b-Instruct" "cot" "random-skipping-baseline-Llama-3b-Instruct"
