#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=368640
#SBATCH --ntasks-per-node=1
#SBATCH --time=4:00:00
#SBATCH --job-name=llama8b_baseline
#SBATCH --output=job_logs/cot/llama8b_baseline-%A.out

cd $HOME/GateSkip

. jobs/environment.sh

srun python -m experiment \
  --model-name "meta-llama/Llama-3.1-8B" \
  --dataset csqa_gsm8k_gen \
  --pretrained \
  --batch-size 1 \
  --eval-batch-size 16 \
  --seq-length 4096 \
  --learning-rate 3e-6 \
  --warmup-steps 1000 \
  --lr-decay-steps 6800 \
  --max-epochs 1 \
  --finetune-mode full \
  --experiment-name llama8b_baseline \
  --save-to-checkpoint llama8b_baseline \
  --project-name gateskip \
  --enable-logging
 
srun python -m experiment \
  --model-name "meta-llama/Llama-3.1-8B" \
  --pretrained \
  --eval-batch-size 32 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics csqa_gen,gsm8k,piqa_gen \
  --num-fewshot 0 \
  --experiment-name llama8b_baseline \
  --load-from-checkpoint llama8b_baseline \
  --project-name gateskip
