#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=5:00:00
#SBATCH --job-name=llama1b_gateskip_selfspec
#SBATCH --output=job_logs/cot/llama1b_gateskip_selfspec-%A.out

cd $HOME/GateSkip

. jobs/environment.sh

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-gating \
  --skip-modules \
  --use-self-speculative-decoding \
  --self-speculative-budget 0.2 \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics csqa_gen,gsm8k,piqa_gen \
  --num-fewshot 0 \
  --experiment-name llama1b_gateskip_selfspec \
  --load-from-checkpoint llama1b_gateskip_selfspec \
  --project-name gateskip
