#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=2:00:00
#SBATCH --job-name=llama1b_baseline_mmlu_gen
#SBATCH --output=job_logs/cot/llama1b_baseline_mmlu_gen-%A.out

cd $HOME/GateSkip

. jobs/environment.sh

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-gating \
  --no-one-gate-per-layer \
  --skip-modules \
  --randomly-skip \
  --no-actually-gate \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics mmlu_gen \
  --num-fewshot 0 \
  --experiment-name llama1b_baseline \
  --load-from-checkpoint llama1b_baseline \
  --project-name gateskip
