#!/bin/bash -l

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=8:00:00
#SBATCH --job-name=llama1b_deebert
#SBATCH --output=job_logs/cot/llama1b_deebert-%A.out

cd "$HOME/GateSkip"

. jobs/environment.sh

srun "${APPTAINER_RUN[@]}" "${PYTHON_BIN}" -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-early-exit \
  --confidence-measure entropy \
  --entropy-threshold 1.0 \
  --eval-batch-size 64 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics csqa_gen,gsm8k,piqa_gen \
  --num-fewshot 0 \
  --experiment-name llama1b_deebert \
  --load-from-checkpoint llama1b_baseline \
  --project-name gateskip

