#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=36:00:00
#SBATCH --job-name=llama1b_baseline_continual
#SBATCH --output=job_logs/cot/llama1b_baseline_continual-%A.out
#SBATCH --exclude=gcn131

cd $HOME/GateSkip

. jobs/environment.sh

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --dataset fineweb \
  --pretrained \
  --batch-size 1 \
  --eval-batch-size 16 \
  --seq-length 512 \
  --learning-rate 3e-6 \
  --warmup-steps 1000 \
  --lr-decay-steps 100000000 \
  --max-epochs 1 \
  --max-hours 24 \
  --finetune-mode full \
  --experiment-name llama1b_baseline_continual \
  --save-to-checkpoint llama1b_baseline_continual \
  --project-name gateskip \
  --enable-logging

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --dataset csqa_gsm8k_gen \
  --pretrained \
  --batch-size 1 \
  --eval-batch-size 16 \
  --seq-length 4096 \
  --learning-rate 3e-6 \
  --warmup-steps 1000 \
  --lr-decay-steps 12000 \
  --max-epochs 1 \
  --finetune-mode full \
  --experiment-name llama1b_baseline_continual_cot \
  --save-to-checkpoint llama1b_baseline_continual_cot \
  --load-from-checkpoint llama1b_baseline_continual \
  --project-name gateskip \
  --enable-logging
 
srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics csqa_gen,gsm8k,piqa_gen \
  --num-fewshot 0 \
  --experiment-name llama1b_baseline \
  --load-from-checkpoint llama1b_baseline_continual_cot \
  --project-name gateskip
