#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=4:00:00
#SBATCH --job-name=llama1b_vector_individual_gate_no_gates
#SBATCH --output=job_logs/cot/llama1b_vector_individual_gate_no_gates-%A.out

cd $HOME/GateSkip

. jobs/environment.sh

srun python -m experiment \
  --model-name "meta-llama/Llama-3.2-1B" \
  --pretrained \
  --use-gating \
  --no-actually-gate \
  --skip-modules \
  --eval-batch-size 128 \
  --seq-length 4096 \
  --finetune-mode full \
  --mode evaluate \
  --evaluation-metrics csqa_gen,gsm8k \
  --num-fewshot 0 \
  --experiment-name llama1b_vector_individual_gate_no_gates \
  --load-from-checkpoint llama1b-csqa-gsm8k-gen-vector \
  --project-name gateskip
